# Loops

There are times where you will need to <ins>**_apply a code multiple times or access all elements of a list or an array_**</ins>. Instead of copying and pasting many times, we can use <ins>**loops**</ins>.

<img src="https://timmousk.com/wp-content/uploads/2022/03/2-6.jpg">

By the end of this section you will learn:
* [**to explore the individual elements of lists and arrays**](#Indexing)
* [**about ```for``` and ```while``` loops**](#Types-of-Loops)

## Indexing

**Indexing** helps <ins>**explore an individual element or elements**</ins> in lists and arrays. Within lists and arrays the <ins>**first element is indexed as 0, then the next element is 1, and so on**</ins>.

<img src = "https://scaler.com/topics/images/Python-list-index-1-1024x498.jpeg" >

To return an element of a list or array, we can type:

**``` list[n] ```**

where **```n```** is the index of the element. An example of returning the third element of a list is:

In [6]:
list = ['a','b','c','d']
print(list[2])

c


The last element can also be indexed as -1, which will result in a decreasing order. The second to last will be -2, and so on.

In [9]:
list = ['a','b','c','d']
print(list[-3])

b


Let's say we wanted to return every other element of our list or array. We could do so by using a semi-colon **```:```**.

In [11]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
odds = array[::2] # this 2 means it will print out every other element, the first semi-colon signifies starting at the first index
print(odds)

evens = array[1::2] # this means we will print out every other element starting at the second index
print(evens)

[1 3 5 7]
[2 4 6 8]


We can also find at what index a certain element occurs at. Here we have a list and use the **```index()```** built-in python function to find at which index '3' occurs at.

In [14]:
list = [1, 2, 3, 4, 5, 6, 7, 8]
result = list.index(3)
print(result)

2


## Types of Loops

### ```for``` loops

One type of loop is **```for```** loops which are also known as <ins>**"definite loops."**</ins> These loops allow you to <ins>**apply code to all elements or a set of indices with a defined termination**</ins> set by the user. It follows this basic format:

```python
for item in group :
    do this thing to the current item
    when done with items, run the rest of the code
```

An example is:

In [1]:
# Here we are telling the for loop to print each item in the group
for item in [34, 17, 12]:
    print(item)

34
17
12


We can also use **```for``` loops** to <ins>**return certain indices**</ins> within a list or array.

In [5]:
import numpy as np
items = np.array([2, 4, 6, 8])

for i in [0,2]:
    print(items[i])
print("finished!!") # print that we have finished our loop!

2
6
finished!!


### ```while``` loops

A **```while```** loop <ins>**applies code to elements until a condition is not met**</ins>. Once the condition is not met, it will continue on to the rest of the code. **```while```** loops are also known as <ins>**"indefinite loops."**</ins> It follows this basic format:

```python
while some condition :
    do something, if the condition is met
    when the condition is no longer met, do rest of code
```

**```while```** loops are great if you have a certain condiiton to meet for a group of elements. *However*, you have to make sure to <ins>**avoid an infinite loop**</ins>. An example of avoiding an infinite loop is:

In [8]:
flag = 1

# the below while loop will continue as long as flag has a value less than 7
while flag < 7:
    print(flag) # here, we are printing our current flag value
    flag = flag + 1 # now, we are increasing the value of flag to avoid an infinite loop
print("finished!!")

1
2
3
4
5
6
finished!!


## Summary

* **[Loops](#Loops)** are used to
    * access **_all_** elements of lists and arrays
    * apply blocks of codes **multiple times**


* **[Indexing](#Indexing)** allows you to access **individual** elements of lists and arrays


* **[```for```](#for-loops)** loops are **definite loops**, which have an ending determined by the user


* **[```while```](#while-loops)** loops are **indefinite loops**, which end once a condition is no longer met

## Exercises

1. **Return the last four values** of the array ```co2```.

In [1]:
import numpy as np
co2 = np.array([2.4, 4.3, 5.9, 1.2, 3.8, 9.8, 0.7])

print(co2[-4:])

[1.2 3.8 9.8 0.7]


2. **Create a ```for loop```** which adds 1 to the first and fourth index of the array ```h2o```.

In [2]:
import numpy as np
h2o = np.array([7.8, 21.8, 3.9, 1.5, 6.8, 11.4, 17.2])

for i in np.array([1, 4]):
    h2o[i] += 1
    
print(h2o)

[ 7.8 22.8  3.9  1.5  7.8 11.4 17.2]


3. **Create a ```while``` loop** which returns a value less than 5 from the array ```items``` divided by 2, and prints "finished!!" when done.

In [3]:
import numpy as np
items = np.array([2, 1, 4, 7, 8])
n = 0

while n < 5:
    print(items[n]/2)
    n += 1
    
print("finished!!")

1.0
0.5
2.0
3.5
4.0
finished!!
